# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-17 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_content', models.CharField(max_length=256)),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalBlog.UserInfo')),
            ],
        ),
    ]
